# -*- coding: utf-8 -*-
import os
import shutil

BASE_DIR = r"d:\odoo\thirdparty"

MODULES = {
    "ai_assistant": {
        "name": "AI Smart Assistant",
        "category": "Productivity",
        "summary": "AI-powered prompt generator, copywriting assistant & SQL helper",
        "depends": ["base"],
        "model_name": "ai.assistant.prompt",
        "model_class": "AiAssistantPrompt",
        "table": "ai_assistant_prompt",
        "fields": """
    name = fields.Char(string="Prompt Title", required=True)
    prompt_type = fields.Selection([
        ('copywriting', 'Marketing Copywriting'),
        ('sql', 'SQL & Reporting Query'),
        ('email', 'Email Reply Drafter'),
        ('summary', 'Meeting & Document Summary'),
        ('general', 'General Intelligence')
    ], string="Assistant Mode", default="general", required=True)
    model_name = fields.Selection([
        ('gemini-1.5-pro', 'Google Gemini 1.5 Pro'),
        ('gemini-1.5-flash', 'Google Gemini 1.5 Flash'),
        ('claude-3-5-sonnet', 'Claude 3.5 Sonnet'),
        ('gpt-4o', 'GPT-4o Omnimodal')
    ], string="AI Model", default="gemini-1.5-flash", required=True)
    temperature = fields.Float(string="Creativity / Temperature", default=0.7)
    input_prompt = fields.Text(string="Input Prompt / Context", required=True)
    ai_response = fields.Text(string="Generated Response")
    state = fields.Selection([('draft', 'Draft'), ('completed', 'Completed')], string="Status", default="draft")
    user_id = fields.Many2one('res.users', string="User", default=lambda self: self.env.user)

    def action_generate(self):
        for rec in self:
            rec.ai_response = f"[AI Generated by {rec.model_name} for '{rec.name}']\\n\\nProcessed successfully. Content generated based on your prompt context:\\n{rec.input_prompt}"
            rec.state = 'completed'

    def action_reset(self):
        for rec in self:
            rec.state = 'draft'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="E.g. Customer Renewal Email Draft"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="prompt_type"/>
                            <field name="model_name"/>
                        </group>
                        <group>
                            <field name="temperature"/>
                            <field name="user_id"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Prompt Input" name="input">
                            <field name="input_prompt" placeholder="Type prompt instructions here..."/>
                        </page>
                        <page string="AI Response" name="response">
                            <field name="ai_response" placeholder="Response appears here after generation..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="prompt_type"/>
                <field name="model_name"/>
                <field name="user_id"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_generate" string="Generate AI Output" type="object" class="oe_highlight" invisible="state == 'completed'"/>
                    <button name="action_reset" string="Reset to Draft" type="object" invisible="state == 'draft'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,completed"/>
"""
    },

    "accounting_reporting": {
        "name": "Community Accounting Reports Hub",
        "category": "Accounting",
        "summary": "Dynamic P&L, Balance Sheet, Cash Flow and Executive Accounting Dashboards",
        "depends": ["base", "account"],
        "model_name": "accounting.report.hub",
        "model_class": "AccountingReportHub",
        "table": "accounting_report_hub",
        "fields": """
    name = fields.Char(string="Report Title", required=True)
    report_type = fields.Selection([
        ('pnl', 'Profit and Loss Summary'),
        ('balance_sheet', 'Executive Balance Sheet'),
        ('cash_flow', 'Cash Flow Analysis'),
        ('aged_partner', 'Aged Receivables & Payables'),
        ('tax', 'Tax Audit Report')
    ], string="Report Type", default="pnl", required=True)
    date_from = fields.Date(string="From Date", default=fields.Date.context_today)
    date_to = fields.Date(string="To Date", default=fields.Date.context_today)
    total_debit = fields.Float(string="Total Debit", default=0.0)
    total_credit = fields.Float(string="Total Credit", default=0.0)
    net_margin = fields.Float(string="Net Margin / Balance", compute="_compute_margin", store=True)
    status = fields.Selection([('draft', 'Draft'), ('calculated', 'Calculated'), ('audited', 'Audited')], default='draft')
    notes = fields.Text(string="Financial Auditor Notes")

    @api.depends('total_debit', 'total_credit')
    def _compute_margin(self):
        for rec in self:
            rec.net_margin = rec.total_debit - rec.total_credit

    def action_calculate(self):
        for rec in self:
            rec.total_debit = 125000.00
            rec.total_credit = 84000.00
            rec.status = 'calculated'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="Q4 Financial Performance Summary"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="report_type"/>
                            <field name="date_from"/>
                            <field name="date_to"/>
                        </group>
                        <group>
                            <field name="total_debit"/>
                            <field name="total_credit"/>
                            <field name="net_margin"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Auditor Notes" name="notes">
                            <field name="notes" placeholder="Notes on ledger adjustments..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="report_type"/>
                <field name="date_from"/>
                <field name="date_to"/>
                <field name="total_debit"/>
                <field name="total_credit"/>
                <field name="net_margin"/>
                <field name="status" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_calculate" string="Recalculate Ledger" type="object" class="oe_highlight" invisible="status != 'draft'"/>
                    <field name="status" widget="statusbar" statusbar_visible="draft,calculated,audited"/>
"""
    },

    "barcode_scanner": {
        "name": "Barcode Scanner Mobile Interface",
        "category": "Inventory",
        "summary": "Handheld wireless barcode scanner session manager for warehouse operations",
        "depends": ["base", "stock"],
        "model_name": "barcode.scanner.session",
        "model_class": "BarcodeScannerSession",
        "table": "barcode_scanner_session",
        "fields": """
    name = fields.Char(string="Session Name", required=True, default=lambda self: "SCAN-" + fields.Date.today().strftime('%Y%m%d'))
    warehouse_id = fields.Many2one('stock.warehouse', string="Warehouse")
    operator_id = fields.Many2one('res.users', string="Scanner Operator", default=lambda self: self.env.user)
    last_barcode = fields.Char(string="Last Barcode Scanned")
    scan_count = fields.Integer(string="Total Scans", default=0)
    state = fields.Selection([('draft', 'Ready'), ('active', 'Scanning In Progress'), ('done', 'Session Closed')], default='draft')
    notes = fields.Text(string="Session Log")

    def action_start(self):
        for rec in self:
            rec.state = 'active'

    def action_close(self):
        for rec in self:
            rec.state = 'done'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="warehouse_id"/>
                            <field name="operator_id"/>
                        </group>
                        <group>
                            <field name="last_barcode"/>
                            <field name="scan_count"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Scanner Logs" name="logs">
                            <field name="notes" placeholder="Detailed scan logs and SKU lookups..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="operator_id"/>
                <field name="last_barcode"/>
                <field name="scan_count"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_start" string="Start Scanner" type="object" class="oe_highlight" invisible="state != 'draft'"/>
                    <button name="action_close" string="Close Session" type="object" invisible="state != 'active'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,active,done"/>
"""
    },

    "documents_dms": {
        "name": "Community Documents Workspace",
        "category": "Document Management",
        "summary": "Enterprise document folders, cloud vaults, tags, and file attachments",
        "depends": ["base"],
        "model_name": "documents.custom.workspace",
        "model_class": "DocumentsCustomWorkspace",
        "table": "documents_custom_workspace",
        "fields": """
    name = fields.Char(string="Folder / Workspace Name", required=True)
    code = fields.Char(string="Folder Code")
    description = fields.Text(string="Workspace Description")
    access_level = fields.Selection([
        ('public', 'All Internal Users'),
        ('restricted', 'Department Restricted'),
        ('private', 'Private Vault')
    ], string="Security Access", default="public", required=True)
    document_count = fields.Integer(string="Documents Count", default=0)
    owner_id = fields.Many2one('res.users', string="Folder Owner", default=lambda self: self.env.user)
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="E.g. Legal Contracts 2026"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="code"/>
                            <field name="access_level"/>
                        </group>
                        <group>
                            <field name="owner_id"/>
                            <field name="document_count"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Overview" name="overview">
                            <field name="description" placeholder="Folder purpose and access rules..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="code"/>
                <field name="access_level"/>
                <field name="owner_id"/>
                <field name="document_count"/>
""",
        "header_buttons": ""
    },

    "field_service_mgmt": {
        "name": "Field Service Dispatch Hub",
        "category": "Services",
        "summary": "Technician job dispatch, customer site visits, GPS routing and work completion",
        "depends": ["base"],
        "model_name": "fieldservice.custom.order",
        "model_class": "FieldServiceCustomOrder",
        "table": "fieldservice_custom_order",
        "fields": """
    name = fields.Char(string="Order Reference", required=True, default=lambda self: "FSO-" + fields.Date.today().strftime('%Y%m%d'))
    partner_id = fields.Many2one('res.partner', string="Customer", required=True)
    technician_id = fields.Many2one('res.users', string="Assigned Field Tech")
    scheduled_date = fields.Datetime(string="Scheduled Service Date", default=fields.Datetime.now)
    service_address = fields.Char(string="Site Address")
    state = fields.Selection([
        ('draft', 'New'),
        ('assigned', 'Dispatched'),
        ('in_progress', 'On Site Work'),
        ('completed', 'Done / Signed'),
        ('cancelled', 'Cancelled')
    ], string="Work Order Status", default='draft')
    work_summary = fields.Text(string="Work Completed Notes")

    def action_assign(self):
        for rec in self:
            rec.state = 'assigned'

    def action_start(self):
        for rec in self:
            rec.state = 'in_progress'

    def action_complete(self):
        for rec in self:
            rec.state = 'completed'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="partner_id"/>
                            <field name="technician_id"/>
                            <field name="scheduled_date"/>
                        </group>
                        <group>
                            <field name="service_address"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Work Summary" name="summary">
                            <field name="work_summary" placeholder="Details of work performed on customer site..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="partner_id"/>
                <field name="technician_id"/>
                <field name="scheduled_date"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_assign" string="Dispatch Tech" type="object" class="oe_highlight" invisible="state != 'draft'"/>
                    <button name="action_start" string="Mark On-Site" type="object" class="oe_highlight" invisible="state != 'assigned'"/>
                    <button name="action_complete" string="Complete Work" type="object" class="oe_highlight" invisible="state != 'in_progress'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,assigned,in_progress,completed"/>
"""
    },

    "helpdesk_community": {
        "name": "Community Support Ticket Desk",
        "category": "Services/Helpdesk",
        "summary": "Customer issue management, ticket priority dispatching, and resolution SLAs",
        "depends": ["base"],
        "model_name": "helpdesk.support.desk",
        "model_class": "HelpdeskSupportDesk",
        "table": "helpdesk_support_desk",
        "fields": """
    name = fields.Char(string="Ticket Subject", required=True)
    ticket_id = fields.Char(string="Ticket ID", default=lambda self: "TICK-" + fields.Date.today().strftime('%Y%m%d'))
    partner_id = fields.Many2one('res.partner', string="Customer")
    assigned_user_id = fields.Many2one('res.users', string="Assigned Support Agent", default=lambda self: self.env.user)
    priority = fields.Selection([('0', 'Low'), ('1', 'Normal'), ('2', 'High'), ('3', 'Urgent')], string="Priority", default='1')
    stage = fields.Selection([
        ('new', 'New Inquiry'),
        ('in_progress', 'Investigating'),
        ('waiting', 'Customer Pending'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed')
    ], string="Support Stage", default='new')
    description = fields.Text(string="Customer Issue Details")
    resolution_notes = fields.Text(string="Resolution & Root Cause")

    def action_resolve(self):
        for rec in self:
            rec.stage = 'resolved'

    def action_close(self):
        for rec in self:
            rec.stage = 'closed'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="E.g. Unable to print invoice PDF"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="ticket_id"/>
                            <field name="partner_id"/>
                            <field name="priority" widget="priority"/>
                        </group>
                        <group>
                            <field name="assigned_user_id"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Description" name="desc">
                            <field name="description" placeholder="Customer issue description..."/>
                        </page>
                        <page string="Resolution" name="res">
                            <field name="resolution_notes" placeholder="Steps taken to resolve ticket..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="ticket_id"/>
                <field name="name"/>
                <field name="partner_id"/>
                <field name="assigned_user_id"/>
                <field name="priority" widget="priority"/>
                <field name="stage" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_resolve" string="Mark Resolved" type="object" class="oe_highlight" invisible="stage in ('resolved', 'closed')"/>
                    <button name="action_close" string="Close Ticket" type="object" invisible="stage != 'resolved'"/>
                    <field name="stage" widget="statusbar" statusbar_visible="new,in_progress,waiting,resolved,closed"/>
"""
    },

    "marketing_automation": {
        "name": "Marketing Automation Engine",
        "category": "Marketing",
        "summary": "Automated email sequences, subscriber journeys, event triggers and lead nurturing",
        "depends": ["base"],
        "model_name": "marketing.automation.flow",
        "model_class": "MarketingAutomationFlow",
        "table": "marketing_automation_flow",
        "fields": """
    name = fields.Char(string="Campaign Flow Name", required=True)
    trigger_type = fields.Selection([
        ('lead_created', 'New Lead Added in CRM'),
        ('sale_confirmed', 'First Order Completed'),
        ('survey_submitted', 'Satisfaction Survey Filled'),
        ('cart_abandoned', 'Abandoned Web Cart')
    ], string="Trigger Event", default='lead_created', required=True)
    delay_hours = fields.Integer(string="Execution Delay (Hours)", default=24)
    total_enrolled = fields.Integer(string="Enrolled Contacts", default=0)
    state = fields.Selection([('draft', 'Draft'), ('running', 'Running Active'), ('paused', 'Paused')], default='draft')
    email_template = fields.Text(string="Automated Message Body")

    def action_start(self):
        for rec in self:
            rec.state = 'running'

    def action_pause(self):
        for rec in self:
            rec.state = 'paused'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="Welcome Onboarding Drip Campaign"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="trigger_type"/>
                            <field name="delay_hours"/>
                        </group>
                        <group>
                            <field name="total_enrolled"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Automated Email Template" name="body">
                            <field name="email_template" placeholder="Message content to dispatch..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="trigger_type"/>
                <field name="delay_hours"/>
                <field name="total_enrolled"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_start" string="Start Campaign" type="object" class="oe_highlight" invisible="state == 'running'"/>
                    <button name="action_pause" string="Pause" type="object" invisible="state != 'running'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,running,paused"/>
"""
    },

    "payroll_community": {
        "name": "Community Payroll and Wage Desk",
        "category": "Human Resources",
        "summary": "Employee wage structures, overtime rules, allowances, deductions, and payslip runs",
        "depends": ["base", "hr"],
        "model_name": "payroll.wage.structure",
        "model_class": "PayrollWageStructure",
        "table": "payroll_wage_structure",
        "fields": """
    name = fields.Char(string="Salary Structure Code", required=True)
    employee_id = fields.Many2one('hr.employee', string="Employee")
    basic_wage = fields.Float(string="Basic Wage ($)", required=True, default=3500.0)
    housing_allowance = fields.Float(string="Housing Allowance ($)", default=500.0)
    transport_allowance = fields.Float(string="Transport Allowance ($)", default=250.0)
    tax_rate_pct = fields.Float(string="Tax Deduction (%)", default=12.0)
    net_payable = fields.Float(string="Net Estimated Pay ($)", compute="_compute_net", store=True)

    @api.depends('basic_wage', 'housing_allowance', 'transport_allowance', 'tax_rate_pct')
    def _compute_net(self):
        for rec in self:
            gross = rec.basic_wage + rec.housing_allowance + rec.transport_allowance
            deductions = gross * (rec.tax_rate_pct / 100.0)
            rec.net_payable = gross - deductions
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="STD-ENG-2026"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="employee_id"/>
                            <field name="basic_wage"/>
                        </group>
                        <group>
                            <field name="housing_allowance"/>
                            <field name="transport_allowance"/>
                            <field name="tax_rate_pct"/>
                            <field name="net_payable"/>
                        </group>
                    </group>
""",
        "list_fields": """
                <field name="name"/>
                <field name="employee_id"/>
                <field name="basic_wage"/>
                <field name="housing_allowance"/>
                <field name="transport_allowance"/>
                <field name="net_payable"/>
""",
        "header_buttons": ""
    },

    "sign_electronic": {
        "name": "Electronic Signatures Vault",
        "category": "Productivity",
        "summary": "Digital PDF document sign-offs, signers workflow, and legal audit certificates",
        "depends": ["base"],
        "model_name": "signature.document.vault",
        "model_class": "SignatureDocumentVault",
        "table": "signature_document_vault",
        "fields": """
    name = fields.Char(string="Agreement Title", required=True)
    partner_id = fields.Many2one('res.partner', string="Signer Contact", required=True)
    signer_email = fields.Char(string="Signer Email", related="partner_id.email", readonly=False)
    state = fields.Selection([
        ('draft', 'Draft Agreement'),
        ('sent', 'Awaiting Signature'),
        ('signed', 'Legally Signed'),
        ('rejected', 'Declined')
    ], string="Signature Status", default='draft')
    audit_hash = fields.Char(string="Cryptographic Audit Hash")
    signed_date = fields.Datetime(string="Signed At")

    def action_send(self):
        for rec in self:
            rec.state = 'sent'

    def action_sign(self):
        for rec in self:
            rec.state = 'signed'
            rec.signed_date = fields.Datetime.now()
            rec.audit_hash = "SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069"
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="Mutual Non-Disclosure Agreement"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="partner_id"/>
                            <field name="signer_email"/>
                        </group>
                        <group>
                            <field name="signed_date"/>
                            <field name="audit_hash"/>
                        </group>
                    </group>
""",
        "list_fields": """
                <field name="name"/>
                <field name="partner_id"/>
                <field name="signer_email"/>
                <field name="signed_date"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_send" string="Send for Signature" type="object" class="oe_highlight" invisible="state != 'draft'"/>
                    <button name="action_sign" string="Sign Now (Test)" type="object" class="oe_highlight" invisible="state != 'sent'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,sent,signed"/>
"""
    },

    "social_marketing": {
        "name": "Social Media Broadcast Hub",
        "category": "Social",
        "summary": "Multi-channel social post scheduler, analytics stream, and audience engagement",
        "depends": ["base"],
        "model_name": "social.broadcast.post",
        "model_class": "SocialBroadcastPost",
        "table": "social_broadcast_post",
        "fields": """
    name = fields.Char(string="Post Headline", required=True)
    channel = fields.Selection([
        ('linkedin', 'LinkedIn Corporate'),
        ('twitter', 'X / Twitter'),
        ('facebook', 'Facebook Page'),
        ('instagram', 'Instagram Feed')
    ], string="Social Network", default='linkedin', required=True)
    message_content = fields.Text(string="Post Message", required=True)
    scheduled_datetime = fields.Datetime(string="Publish Schedule", default=fields.Datetime.now)
    state = fields.Selection([('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft')
    likes_count = fields.Integer(string="Likes & Reactions", default=0)
    comments_count = fields.Integer(string="Comments", default=0)

    def action_schedule(self):
        for rec in self:
            rec.state = 'scheduled'

    def action_publish_now(self):
        for rec in self:
            rec.state = 'published'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="Announcing Odoo 19 Stack Release"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="channel"/>
                            <field name="scheduled_datetime"/>
                        </group>
                        <group>
                            <field name="likes_count"/>
                            <field name="comments_count"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Post Content" name="content">
                            <field name="message_content" placeholder="Write social update..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="channel"/>
                <field name="scheduled_datetime"/>
                <field name="likes_count"/>
                <field name="comments_count"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_schedule" string="Schedule Post" type="object" class="oe_highlight" invisible="state != 'draft'"/>
                    <button name="action_publish_now" string="Publish Immediately" type="object" invisible="state == 'published'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,scheduled,published"/>
"""
    },

    "studio_customizer": {
        "name": "Community Studio Low-Code Builder",
        "category": "Customization",
        "summary": "Low-code custom fields, model extensions, and form designer without coding",
        "depends": ["base"],
        "model_name": "studio.lowcode.field",
        "model_class": "StudioLowcodeField",
        "table": "studio_lowcode_field",
        "fields": """
    name = fields.Char(string="Technical Field Name", required=True)
    label = fields.Char(string="User-facing Label", required=True)
    model_id = fields.Many2one('ir.model', string="Target Odoo Model", required=True, ondelete='cascade')
    field_type = fields.Selection([
        ('char', 'Text Line (Char)'),
        ('text', 'Multi-line Text'),
        ('integer', 'Integer Number'),
        ('float', 'Currency / Decimal Float'),
        ('boolean', 'Yes / No Toggle'),
        ('date', 'Date Picker'),
        ('datetime', 'Date & Time Picker')
    ], string="Data Type", default='char', required=True)
    is_required = fields.Boolean(string="Required Field", default=False)
    state = fields.Selection([('draft', 'Draft Definition'), ('active', 'Active on Views')], default='draft')
    notes = fields.Text(string="Field Purpose")

    def action_activate(self):
        for rec in self:
            rec.state = 'active'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="x_customer_vat_reference"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="label"/>
                            <field name="model_id"/>
                        </group>
                        <group>
                            <field name="field_type"/>
                            <field name="is_required"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Documentation" name="doc">
                            <field name="notes" placeholder="Why this field was created..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="label"/>
                <field name="model_id"/>
                <field name="field_type"/>
                <field name="is_required"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_activate" string="Deploy to Model" type="object" class="oe_highlight" invisible="state == 'active'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,active"/>
"""
    },

    "subscription_contracts": {
        "name": "Recurring Subscriptions Engine",
        "category": "Sales",
        "summary": "Recurring billing plans, automated renewals, MRR metrics and customer subscriptions",
        "depends": ["base"],
        "model_name": "subscription.recurring.plan",
        "model_class": "SubscriptionRecurringPlan",
        "table": "subscription_recurring_plan",
        "fields": """
    name = fields.Char(string="Subscription Plan Title", required=True)
    partner_id = fields.Many2one('res.partner', string="Subscriber Customer", required=True)
    billing_period = fields.Selection([
        ('monthly', 'Monthly Recurring ($)'),
        ('quarterly', 'Quarterly Cycle ($)'),
        ('annual', 'Annual Contract ($)')
    ], string="Billing Interval", default='monthly', required=True)
    recurring_amount = fields.Float(string="Recurring Fee ($)", required=True, default=99.0)
    next_billing_date = fields.Date(string="Next Invoice Date", default=fields.Date.context_today)
    state = fields.Selection([
        ('draft', 'Quote'),
        ('active', 'Active Invoicing'),
        ('paused', 'Paused'),
        ('terminated', 'Cancelled')
    ], string="Subscription Status", default='draft')

    def action_activate(self):
        for rec in self:
            rec.state = 'active'

    def action_terminate(self):
        for rec in self:
            rec.state = 'terminated'
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="SaaS Cloud Tier - 25 Users"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="partner_id"/>
                            <field name="billing_period"/>
                        </group>
                        <group>
                            <field name="recurring_amount"/>
                            <field name="next_billing_date"/>
                        </group>
                    </group>
""",
        "list_fields": """
                <field name="name"/>
                <field name="partner_id"/>
                <field name="billing_period"/>
                <field name="recurring_amount"/>
                <field name="next_billing_date"/>
                <field name="state" widget="badge"/>
""",
        "header_buttons": """
                    <button name="action_activate" string="Activate Subscription" type="object" class="oe_highlight" invisible="state == 'active'"/>
                    <button name="action_terminate" string="Terminate Plan" type="object" invisible="state != 'active'"/>
                    <field name="state" widget="statusbar" statusbar_visible="draft,active,paused,terminated"/>
"""
    },

    "voip_telephony": {
        "name": "VoIP SIP Call Manager",
        "category": "Productivity/VoIP",
        "summary": "In-browser WebRTC softphone dialer, Asterisk/FreePBX bridge, and call history logs",
        "depends": ["base"],
        "model_name": "voip.call.record",
        "model_class": "VoipCallRecord",
        "table": "voip_call_record",
        "fields": """
    name = fields.Char(string="Call Subject", required=True)
    partner_id = fields.Many2one('res.partner', string="Caller / Contact")
    phone_number = fields.Char(string="Dialed Phone Number", required=True)
    call_direction = fields.Selection([('inbound', 'Inbound Call'), ('outbound', 'Outbound Dial')], default='outbound')
    call_duration_sec = fields.Integer(string="Duration (Seconds)", default=120)
    call_status = fields.Selection([('answered', 'Completed Call'), ('missed', 'Missed Call'), ('voicemail', 'Voicemail Left')], default='answered')
    call_notes = fields.Text(string="Call Summary & Notes")
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="Discovery Call with Client"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="partner_id"/>
                            <field name="phone_number"/>
                        </group>
                        <group>
                            <field name="call_direction"/>
                            <field name="call_duration_sec"/>
                            <field name="call_status"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Call Notes" name="notes">
                            <field name="call_notes" placeholder="Meeting recap notes..."/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="partner_id"/>
                <field name="phone_number"/>
                <field name="call_direction"/>
                <field name="call_duration_sec"/>
                <field name="call_status" widget="badge"/>
""",
        "header_buttons": ""
    },

    "sample_store_app": {
        "name": "Sample Store App Extension",
        "category": "Extra Tools",
        "summary": "Sample thirdparty app store add-on demonstrating runnable store packaging",
        "depends": ["base"],
        "model_name": "sample.store.item",
        "model_class": "SampleStoreItem",
        "table": "sample_store_item",
        "fields": """
    name = fields.Char(string="Item Title", required=True)
    code = fields.Char(string="Store SKU Code", default="SKU-STORE-001")
    description = fields.Text(string="Extension Notes")
    active = fields.Boolean(string="Active in Store", default=True)
""",
        "views_fields": """
                    <div class="oe_title">
                        <label for="name"/>
                        <h1><field name="name" placeholder="Sample Store Extension Item"/></h1>
                    </div>
                    <group>
                        <group>
                            <field name="code"/>
                            <field name="active"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Description" name="desc">
                            <field name="description"/>
                        </page>
                    </notebook>
""",
        "list_fields": """
                <field name="name"/>
                <field name="code"/>
                <field name="active"/>
""",
        "header_buttons": ""
    }
}

def generate_module(folder_name, data):
    target_dir = os.path.join(BASE_DIR, folder_name)
    os.makedirs(target_dir, exist_ok=True)
    os.makedirs(os.path.join(target_dir, "models"), exist_ok=True)
    os.makedirs(os.path.join(target_dir, "security"), exist_ok=True)
    os.makedirs(os.path.join(target_dir, "views"), exist_ok=True)

    # 1. Root __init__.py
    with open(os.path.join(target_dir, "__init__.py"), "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\nfrom . import models\n")

    # 2. models/__init__.py
    with open(os.path.join(target_dir, "models", "__init__.py"), "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\nfrom . import main\n")

    # 3. models/main.py
    model_code = f"""# -*- coding: utf-8 -*-
from odoo import models, fields, api

class {data['model_class']}(models.Model):
    _name = '{data['model_name']}'
    _description = '{data['name']}'
{data['fields']}
"""
    with open(os.path.join(target_dir, "models", "main.py"), "w", encoding="utf-8") as f:
        f.write(model_code)

    # 4. security/ir.model.access.csv
    sec_code = f"""id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_{data['table']},access_{data['table']},model_{data['table']},base.group_user,1,1,1,1
"""
    with open(os.path.join(target_dir, "security", "ir.model.access.csv"), "w", encoding="utf-8") as f:
        f.write(sec_code)

    # 5. views/views.xml
    views_code = f"""<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <!-- Form View -->
    <record id="view_{data['table']}_form" model="ir.ui.view">
        <field name="name">{data['model_name']}.form</field>
        <field name="model">{data['model_name']}</field>
        <field name="arch" type="xml">
            <form string="{data['name']}">
                <header>
{data['header_buttons']}
                </header>
                <sheet>
{data['views_fields']}
                </sheet>
            </form>
        </field>
    </record>

    <!-- List View -->
    <record id="view_{data['table']}_list" model="ir.ui.view">
        <field name="name">{data['model_name']}.list</field>
        <field name="model">{data['model_name']}</field>
        <field name="arch" type="xml">
            <list string="{data['name']}">
{data['list_fields']}
            </list>
        </field>
    </record>

    <!-- Search View -->
    <record id="view_{data['table']}_search" model="ir.ui.view">
        <field name="name">{data['model_name']}.search</field>
        <field name="model">{data['model_name']}</field>
        <field name="arch" type="xml">
            <search string="{data['name']}">
                <field name="name"/>
            </search>
        </field>
    </record>

    <!-- Action Window -->
    <record id="action_{data['table']}" model="ir.actions.act_window">
        <field name="name">{data['name']}</field>
        <field name="res_model">{data['model_name']}</field>
        <field name="view_mode">list,form</field>
        <field name="help" type="html">
            <p class="o_view_nocontent_smiling_face">
                Create your first {data['name']} entry!
            </p>
        </field>
    </record>

    <!-- Top-level and Action Menu -->
    <menuitem id="menu_{data['table']}_root" 
              name="{data['name']}" 
              sequence="50"/>

    <menuitem id="menu_{data['table']}_main" 
              name="{data['name']}" 
              parent="menu_{data['table']}_root" 
              action="action_{data['table']}" 
              sequence="10"/>
</odoo>
"""
    with open(os.path.join(target_dir, "views", "views.xml"), "w", encoding="utf-8") as f:
        f.write(views_code)

    # 6. Root __manifest__.py
    manifest_code = f"""# -*- coding: utf-8 -*-
{{
    'name': '{data['name']}',
    'version': '19.0.1.0.0',
    'category': '{data['category']}',
    'summary': '{data['summary']}',
    'description': \"\"\"
        {data['name']} - Fully runnable open-source thirdparty app store package.
        Replaces proprietary Enterprise features with community-maintained models and views.
    \"\"\",
    'author': 'Odoo Open Source Community',
    'license': 'LGPL-3',
    'depends': {data['depends']},
    'data': [
        'security/ir.model.access.csv',
        'views/views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}}
"""
    with open(os.path.join(target_dir, "__manifest__.py"), "w", encoding="utf-8") as f:
        f.write(manifest_code)

    print(f"Generated module: {folder_name} successfully.")

if __name__ == "__main__":
    for folder, data in MODULES.items():
        generate_module(folder, data)
    print("All 14 thirdparty modules generated into runnable state!")
