services:
  web:
    image: odoo:${ODOO_IMAGE_TAG:-18.0}
    container_name: odoo_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${ODOO_PORT:-8069}:8069"
      - "${ODOO_CHAT_PORT:-8072}:8072"
    environment:
      - HOST=db
      - PORT=5432
      - USER=${POSTGRES_USER:-odoo}
      - PASSWORD=${POSTGRES_PASSWORD:-odoo}
    volumes:
      - ./config:/etc/odoo
      - ./oca:/mnt/extra-addons/oca
      - ./thirdparty:/mnt/extra-addons/thirdparty
      - ./custom:/mnt/extra-addons/custom
      - odoo-web-data:/var/lib/odoo
    restart: unless-stopped
    networks:
      - odoo-network

  db:
    image: postgres:${POSTGRES_VERSION:-16}
    container_name: odoo_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - odoo-network

volumes:
  odoo-web-data:
    name: odoo_web_data
  odoo-db-data:
    name: odoo_db_data

networks:
  odoo-network:
    name: odoo_network
    driver: bridge
