[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/oca,/mnt/extra-addons/oca/dms,/mnt/extra-addons/oca/helpdesk,/mnt/extra-addons/oca/contract,/mnt/extra-addons/oca/stock-logistics-barcode,/mnt/extra-addons/oca/delivery-carrier,/mnt/extra-addons/oca/account-financial-reporting,/mnt/extra-addons/oca/account-financial-tools,/mnt/extra-addons/oca/payroll,/mnt/extra-addons/oca/server-tools,/mnt/extra-addons/oca/server-ux,/mnt/extra-addons/oca/reporting-engine,/mnt/extra-addons/thirdparty,/mnt/extra-addons/custom
admin_passwd = MasterAdmin_Secured_2026!
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = Odoo_SecuredDBPass_2026!
db_name = odoo
proxy_mode = True
log_level = info
workers = 0
max_cron_threads = 2
list_db = True
